### ISSUE TITLE
Module Info event null reference exception

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1065]
## EDDI version in which issue found
3.3.2

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
No unhandled exceptions

## Observed
System.NullReferenceException: Object reference not set to an instance of an object. 
at EddiShipMonitor.ShipMonitor.handleModuleInfoEvent(ModuleInfoEvent event) 

## Investigation
https://rollbar.com/EDCD/EDDI/items/10277/?item_page=0&#instances
Please click on timestamps to review individual reports.

**Comment by Tkael** [comment]
```
   at EddiShipMonitor.ShipMonitor.handleModuleInfoEvent(ModuleInfoEvent event) in EDDI\ShipMonitor\ShipMonitor.cs:line 845
   at EddiShipMonitor.ShipMonitor.PreHandle(Event event) in EDDI\ShipMonitor\ShipMonitor.cs:line 233
   at Eddi.EDDI.OnEvent(Event event)
```

**Comment by Hoodathunk** [comment]
Yup, interesting that the thrusters were not set. Was wondering if it was one of the fixed modules. What was the ship?

Anyway, I saw your PR, I concur.

**Comment by Tkael** [comment]
Krait Phantom. Probably an issue with one of the new ship-specific modules. I'll investigate that further.

**Comment by Tkael** [comment]
Yep, the cockpit module was undefined.
