### ISSUE TITLE
EDDP Monitor: Exceptions thrown for watched systems

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#120]
## Steps to reproduce

1. subscribe to faction state changes for factions (for example, w/in 50 ly of your current location)
2. enable verbose logging and observe the log during faction state changes received by the EDDP monitor

## Expected
No exceptions thrown

## Observed
Example logs:
```
2017-09-28T03:38:57 EddpMonitor:monitor [D] Message is {"newsecurity":"Low","newstate":"None","oldsecurity":"Medium","oldstate":"Boom","systemname":"Aymarahuara","x":-151.5,"y":39.40625,"z":-74.1875} 
2017-09-28T03:38:57 EddpMonitor:monitor [E] Caught exception System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiEddpMonitor.EddpMonitor.match(String systemname, String stationname, Decimal x, Decimal y, Decimal z, String oldfaction, String newfaction, String oldstate, String newstate)
   at EddiEddpMonitor.EddpMonitor.handleSystemDelta(JObject json)
   at EddiEddpMonitor.EddpMonitor.monitor()
2017-09-28T03:39:58 EddpMonitor:monitor [D] Message is {"newstate":"Outbreak","oldstate":"None","systemname":"Ewenks","x":143.6875,"y":44.59375,"z":-20.5625} 
2017-09-28T03:39:58 EddpMonitor:monitor [E] Caught exception System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiEddpMonitor.EddpMonitor.match(String systemname, String stationname, Decimal x, Decimal y, Decimal z, String oldfaction, String newfaction, String oldstate, String newstate)
   at EddiEddpMonitor.EddpMonitor.handleSystemDelta(JObject json)
   at EddiEddpMonitor.EddpMonitor.monitor()
```

## Investigation
Needs further investigation

**Comment by Tkael** [comment]
fix tested & working. closing issue.
