### ISSUE TITLE
New bug with Star scanned script from `feature/scan-overhaul2`

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1310]
## EDDI version in which issue is found
Branch `feature/scan-overhaul2`

## VoiceAttack version in which issue is found (as applicable)
Standalone

## Steps to reproduce
1. Jumped into `Eactaiky AH-B c27-13` and honked the FSS.

## Expected
Normal scan report.

## Observed
EDDI said:
```
There is a problem with the: Star scanned script. Exception has been thrown by the target of an invocation.
```

## Investigation
L:og shows:
```
2019-05-22T21:32:56 [Warning] ScriptResolver:resolveScript Failed to resolve the: Star scanned script. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EddiDataDefinitions.StarSystem.get_materialEdNames() in C:\dev\EDDI\DataDefinitions\StarSystem.cs:line 133
   at EddiDataDefinitions.StarSystem.get_isgold() in C:\dev\EDDI\DataDefinitions\StarSystem.cs:line 108
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Cottle.Values.ReflectionValue.MemberReader.<>c__DisplayClass6_0.<.ctor>b__0(Object s)
   at Cottle.Values.ReflectionValue.MemberReader.Extract(Object source)
   at Cottle.Values.ReflectionValue.Resolve()
   at Cottle.Values.ResolveValue.Acquire()
   at Cottle.Values.ResolveValue.get_Fields()
   at Cottle.Documents.Simple.Evaluators.AccessEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.EchoNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.SimpleDocument.Render(IStore store, TextWriter writer)
   at Cottle.Documents.AbstractDocument.Render(IStore store)
   at EddiSpeechResponder.ScriptResolver.resolveScript(String script, BuiltinStore store, Boolean master, Script scriptObject) in C:\dev\EDDI\SpeechResponder\ScriptResolver.cs:line 88 
```

**Comment by richardbuckle** [comment]
At first glance might be some code mutating a collection that it shouldn't be. A common concurrency issue.

**Comment by JCalvertJoshua** [comment]
Just to let you know I had the same error (I think) just now visiting two other systems.
Here's my log:
[eddi.log](https://github.com/EDCD/EDDI/files/3244527/eddi.log)

**Comment by richardbuckle** [comment]
> UPDATE: After a restart I jumped to both systems again. This time the errors didn't appear.

Yes, that's to be expected. It's a concurrency issue so it doesn't manifest in a deterministic way.
