### ISSUE TITLE
Failed to load monitor: EddiCrimeMonitor.dll

### ISSUE THREAD

**Issue by Juddz** [EDCD/EDDI#1322]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.4.0
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
1.7.5
## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
I installed 2.3 as that is the first version I found when looking for EDDI and this worked perfectly.
It advised me that a later version was available but failed to download it so I went looking for the latest version and found 3.4.0 at this new repository.
I installed over the top of 2.3 and upon running, the configuration window tried to open but it is blank.
I closed this via task manager and opened voice attack. VA reported the plugin working fine but when I tried to use the voice command to open the config file it did the same as before.
Several reboots, uninstall/reinstall and following the advice on the troubleshooting page have not helped.
## Expected
[Describe what you expected to happen]
I expected the config page to open.
## Observed
[Describe what happened instead]
Eventually, after several iterations of install/uninstall, the text-to-speech gave me an error which I found in the eddi.log file:
2019-05-29T11:19:41 [Info] EDDI:.ctor EDDI 3.4.0 starting 
2019-05-29T11:19:41 [Info] EDDI:.ctor On live 
2019-05-29T11:19:41 [Info] CargoMonitor:initializeCargoMonitor Initialised Cargo monitor 1.0.0 
2019-05-29T11:19:41 [Error] EDDI:findMonitors Failed to load monitor: EddiCrimeMonitor.dll.
Exception has been thrown by the target of an invocation. Could not load type 'EddiDataDefinitions.Target' from assembly 'EddiDataDefinitions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. {"ClassName":"System.Reflection.TargetInvocationException","Message":"Exception has been thrown by the target of an invocation.","Data":null,"InnerException":{"ClassName":"System.TypeLoadException","Message":"Could not load type 'EddiDataDefinitions.Target' from assembly 'EddiDataDefinitions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at EddiCrimeMonitor.CrimeMonitor..ctor()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.ctor\nEddiCrimeMonitor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\nEddiCrimeMonitor.CrimeMonitor\nVoid .ctor()","HResult":-2146233054,"Source":"EddiCrimeMonitor","WatsonBuckets":null,"TypeLoadClassName":"EddiDataDefinitions.Target","TypeLoadAssemblyName":"EddiDataDefinitions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","TypeLoadMessageArg":null,"TypeLoadResourceID":-2146233054},"HelpURL":null,"StackTraceString":"   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)\r\n   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)\r\n   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)\r\n   at System.Activator.CreateInstance(Type type, Boolean nonPublic)\r\n   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)\r\n   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)\r\n   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)\r\n   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)\r\n   at Eddi.EDDI.findMonitors()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nCreateInstance\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.RuntimeTypeHandle\nSystem.Object CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)","HResult":-2146232828,"Source":"mscorlib","WatsonBuckets":null}
2019-05-29T11:19:41 [Error] EDDI:findMonitors Failed to load monitor: EddiCrimeMonitor.dll.
Exception has been thrown by the target of an invocation. Could not load type 'EddiDataDefinitions.Target' from assembly 'EddiDataDefinitions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. System.Collections.Generic.Dictionary`2[System.String,System.Object]
2019-05-29T11:19:41 [Info] MaterialMonitor:.ctor Initialised Material monitor 1.0.0 
2019-05-29T11:19:42 [Info] MissionMonitor:initializeMissionMonitor Initialised Mission monitor 1.0.0 
2019-05-29T11:19:42 [Info] ShipMonitor:.ctor Initialised Ship Monitor 1.0.0 
2019-05-29T11:19:42 [Info] StatusMonitor:.ctor Initialised Status monitor 1.0.0 
2019-05-29T11:19:42 [Info] EDDNResponder:.ctor Initialised EDDN responder 1.0.0 
2019-05-29T11:19:42 [Info] EDSMResponder:.ctor Initialised EDSM responder 1.0.0 
2019-05-29T11:19:42 [Warning] Events:.cctor Exception:  System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at EddiEvents.Events..cctor()
2019-05-29T11:19:42 [Info] SpeechResponder:.ctor Initialised Speech responder 1.0.0 
2019-05-29T11:19:42 [Info] VoiceAttackResponder:.ctor Started VoiceAttack responder 
2019-05-29T11:19:42 [Info] EDDI:.ctor EDDI access to the companion app is disabled 
2019-05-29T11:19:42 [Info] EDDI:.ctor EDDI 3.4.0 initialised 
2019-05-29T11:19:42 [Info] EDDI:Start Starting keepalive for EDDP monitor 
2019-05-29T11:19:42 [Info] EDDI:Start Starting keepalive for Journal monitor 
2019-05-29T11:19:42 [Info] EDDI:keepAlive Starting EDDP monitor (0) 
2019-05-29T11:19:42 [Info] EDDI:keepAlive Starting Journal monitor (0) 
2019-05-29T11:19:42 [Info] EDDI:Start Starting keepalive for Mission monitor 
2019-05-29T11:19:42 [Info] EDDI:keepAlive Starting Mission monitor (0) 
2019-05-29T11:19:42 [Info] EDDI:Start Starting keepalive for Status monitor 
2019-05-29T11:19:42 [Info] EDDI:keepAlive Starting Status monitor (0) 
2019-05-29T11:19:42 [Info] EDDI:Start Started EDDN responder 
2019-05-29T11:19:42 [Warning] EDDI:Start Failed to start EDSM responder 
2019-05-29T11:19:42 [Info] EDDI:Start Started Speech responder 
2019-05-29T11:19:42 [Warning] EDDI:Start Failed to start VoiceAttack responder 
2019-05-29T11:19:43 [Info] EDDI:eventFileHeader On live 

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
I have tried following advice on the troubleshooting page.
I have uninstalled completely (including %appdata%) and reinstalled all versions from 2.3 to 3.4.1b and only 2.3 works. All others just hang on a blank screen.
Also tried searching for this error before opening a ticket but found nothing.

**Comment by Hoodathunk** [comment]
The json files are significantly different between 2.3 (very old) and 3.4. Try the troubleshooting steps at https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md and get back to us if that doesn’t resolve it.

**Comment by Juddz** [comment]
I've tried the troubleshooting steps under 'eddi won't launch/crashes on startup' and get the same result.
The window tries to open but just hangs

**Comment by Hoodathunk** [comment]
Did you remove the `EDDI` folder from the Voice Attack `Apps` folder and then install 3.4.1-b1, or did you install over previous versions?

**Comment by Juddz** [comment]
I tried both methods. I have installed over previous versions with a higher version and I have completely removed all traces of the program and appdata and installed a previous version.

**Comment by Tkael** [comment]
The crime monitor and associated definitions are new with version 3.4.1-b1 (which you apparently installed after clearing your prior installation and before installing version 3.4.0). I think EDDI is seeing the EddiCrimeMonitor.dll file in your install folder and attempting to load it, even though version 3.4.0 isn't compatible yet.

Please either completely delete EDDI from your install folder then reinstall clean with version 3.4.0 or try installing version 3.4.1-b1?

**Comment by Tkael** [comment]
I've submitted PR #1324 addressing what I believe is the source of this issue.

**Comment by Juddz** [comment]
OK, so I have reinstalled 4.3.1 and got the same issue and so then once again uninstalled the program using the uninstaller which removed the folder and then manually removed the %appdata% folder.
Once again, starting as clean as I can, I installed 3.4.0 and allowed the program to install and run from the installer. This brings the same, empty, non-responsive program window and just sits there doing nothing.
Again, if I load voice attack, the EDDI is very obviously working and works amazingly well but even using the 'open eddi' voice command I am faced with an empty window and no configuration screen.
I feel a screen shot is a little redundant but I've added them anyway.
![EDDI Settings 3 4 1](https://user-images.githubusercontent.com/17096691/58617234-83995180-82b7-11e9-8463-42c52a3fb55a.png)
![EDDI Settings](https://user-images.githubusercontent.com/17096691/58617235-83995180-82b7-11e9-8c1a-5e2c88032098.png)

**Comment by Juddz** [comment]
I'm not all that up on github - does closed mean there's nothing else to suggest to fix this or did I miss something?

**Comment by Tkael** [comment]
It means that we've incorporated a change that we think will fix the issue. That said, if 3.4.1-b1 isn't working then I'm interested in seeing your log from trying to open 3.4.1-b1.

**Comment by Tkael** [comment]
Have you tried manually deleting VoiceAttack/Apps/EDDI rather than using the uninstaller?

**Comment by Juddz** [comment]
Yes, I tried that to start with and then used the uninstaller in case manually deleting didn't remove everything but just to be sure, as I am writing this I will delete everything manually and install 3.4.1 and post the log...
OK, so I have done that, run eddi from the launcher and while it is sat there being unresponsive I have copied the log file:
2019-05-30T13:24:25 [Info] EDDI:.ctor EDDI 3.4.1-b1 starting 
2019-05-30T13:24:25 [Info] EDDI:.ctor On live 
2019-05-30T13:24:25 [Info] CargoMonitor:initializeCargoMonitor Initialised Cargo monitor 1.0.0 
2019-05-30T13:24:25 [Info] CrimeMonitor:initializeCrimeMonitor Initialised Crime monitor 1.0.0 
2019-05-30T13:24:25 [Info] MaterialMonitor:.ctor Initialised Material monitor 1.0.0 
2019-05-30T13:24:26 [Info] MissionMonitor:initializeMissionMonitor Initialised Mission monitor 1.0.0 
2019-05-30T13:24:26 [Info] ShipMonitor:.ctor Initialised Ship Monitor 1.0.0 
2019-05-30T13:24:26 [Info] StatusMonitor:.ctor Initialised Status monitor 1.0.0 
2019-05-30T13:24:26 [Info] StarSystemSqLiteRepository:CreateDatabase Updating starsystem repository (1) 
2019-05-30T13:24:26 [Info] EDDNResponder:.ctor Initialised EDDN responder 1.0.0 
2019-05-30T13:24:26 [Info] EDSMResponder:.ctor Initialised EDSM responder 1.0.0 
2019-05-30T13:24:29 [Info] SpeechResponder:.ctor Initialised Speech responder 1.0.0 
2019-05-30T13:24:29 [Info] VoiceAttackResponder:.ctor Started VoiceAttack responder 
2019-05-30T13:24:29 [Info] EDDI:.ctor EDDI access to the companion app is disabled 
2019-05-30T13:24:29 [Info] EDDI:.ctor EDDI 3.4.1-b1 initialised 
2019-05-30T13:24:29 [Info] EDDI:Start Starting keepalive for EDDP monitor 
2019-05-30T13:24:29 [Info] EDDI:Start Starting keepalive for Journal monitor 
2019-05-30T13:24:29 [Info] EDDI:keepAlive Starting EDDP monitor (0) 
2019-05-30T13:24:29 [Info] EDDI:keepAlive Starting Journal monitor (0) 
2019-05-30T13:24:29 [Info] EDDI:Start Starting keepalive for Mission monitor 
2019-05-30T13:24:29 [Info] EDDI:keepAlive Starting Mission monitor (0) 
2019-05-30T13:24:29 [Info] EDDI:Start Starting keepalive for Status monitor 
2019-05-30T13:24:29 [Info] EDDI:keepAlive Starting Status monitor (0) 
2019-05-30T13:24:29 [Info] EDDI:Start Started EDDN responder 
2019-05-30T13:24:29 [Warning] EDDI:Start Failed to start EDSM responder 
2019-05-30T13:24:29 [Info] EDDI:Start Started Speech responder 
2019-05-30T13:24:29 [Warning] EDDI:Start Failed to start VoiceAttack responder 
2019-05-30T13:24:29 [Info] EDDI:eventFileHeader On live 
2019-05-30T13:24:29 [Info] EDDI:eventLocation Location StarSystem: Aramzahd 
2019-05-30T13:24:31 [Warning] JournalMonitor:ParseJournalEntry EDDI has no handler for event type 'Powerplay'./r/nRaw event:/r/n{ "timestamp":"2019-05-30T12:31:50Z", "event":"Powerplay", "Power":"Aisling Duval", "Rank":0, "Merits":0, "Votes":0, "TimePledged":8030248 } 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Warzone_PointRace_High:#index=1 in resource EddiDataDefinitions.Properties.SignalSource 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Warzone_PointRace_Low:#index=1 in resource EddiDataDefinitions.Properties.SignalSource 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Warzone_PointRace_Med:#index=1 in resource EddiDataDefinitions.Properties.SignalSource 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Warzone_PointRace_Low:#index=2 in resource EddiDataDefinitions.Properties.SignalSource 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Sensor_FastScan in resource EddiDataDefinitions.Properties.Modifications 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Misc_LightWeight in resource EddiDataDefinitions.Properties.Modifications 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Sensor_LightWeight in resource EddiDataDefinitions.Properties.Modifications 
2019-05-30T13:24:31 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Sensor_Expanded in resource EddiDataDefinitions.Properties.Modifications 
2019-05-30T13:24:32 [Info] EDDI:eventJumped Jumped to Paras 
2019-05-30T13:24:33 [Warning] JournalMonitor:ParseJournalEntry EDDI has no handler for event type 'Powerplay'./r/nRaw event:/r/n{ "timestamp":"2019-05-30T12:42:50Z", "event":"Powerplay", "Power":"Aisling Duval", "Rank":0, "Merits":0, "Votes":0, "TimePledged":8030908 }

**Comment by Tkael** [comment]
Well, 3.4.1-b1 appears to have resolved the issue with the crime monitor. You're so getting a blank white window when you try to open EDDI though? Hmm... the log doesn't really give me very many clues for that. Thinking...

**Comment by Juddz** [comment]
I've changed the issue title to more accurately reflect what I believe to be the actual issue.
