### ISSUE TITLE
some weird crashing going on in ax conflict zones

### ISSUE THREAD

**Issue by Orsum-VR** [EDCD/EDDI#1419]
## EDDI version in which issue is found
3.4.2 b1

## VoiceAttack version in which issue is found (as applicable)
v1.7.7

## Steps to reproduce
1. when in ax conflict zones 
2. not sure if its linked to caustic damage

## Expected
no to crash

## Observed
it crashed

## Investigation
2019-07-27T07:33:11 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI heat warning)) 
2019-07-27T07:33:12 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID dee22dfe-9ded-47bc-859b-645029f82f5e:System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at EddiSpeechService.SpeechQueue.filterSpeechQueue(String type, ConcurrentQueue`1& speechQueue, EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.DequeueSpeechOfType(String type)
   at EddiSpeechService.SpeechQueue.dequeueStaleSpeech(EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.Enqueue(EddiSpeech speech)
   at EddiSpeechService.SpeechService.<>c__DisplayClass33_0.<Say>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 
2019-07-27T07:33:12 [Info] EDDI:Stop EDDI 3.4.2-b1 stopped 

here is another example related to ax conflict zones 

((EDDI hull damaged)) 
2019-07-27T07:28:07 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID dee22dfe-9ded-47bc-859b-645029f82f5e:System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at EddiSpeechService.SpeechQueue.filterSpeechQueue(String type, ConcurrentQueue`1& speechQueue, EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.DequeueSpeechOfType(String type)
   at EddiSpeechService.SpeechQueue.dequeueStaleSpeech(EddiSpeech eddiSpeech)
   at EddiSpeechService.SpeechQueue.Enqueue(EddiSpeech speech)
   at EddiSpeechService.SpeechService.<>c__DisplayClass33_0.<Say>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 
2019-07-27T07:28:07 [Info] EDDI:Stop EDDI 3.4.2-b1 stopped

**Comment by Hoodathunk** [comment]
I've seen this recently on assassination missions but haven't had the opportunity to investigate until now. I think I know what's going on.

**Comment by Orsum-VR** [comment]
Ok, thats great to know. Hope you get a fix out for it soon.
