### ISSUE TITLE
Crashed during speach and complains of loss of data 

### ISSUE THREAD

**Issue by badmanj0k3r** [EDCD/EDDI#1641]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
current
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
left eddi running and it just crashes out ...
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/3983736/eddi_issue.zip)

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by richardbuckle** [comment]
Wow. This has to be the laziest post I've seen to date. Gave "current" when told not to. 

Ain't gotr time for this. Deleting.

**Comment by Tkael** [comment]
Version: 3.5.1 (as logged)
Crash source:
```
2019-12-19T11:33:18 [Warning] SpeechService:speak Speech failed:  System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
   at System.Speech.Synthesis.SpeechSynthesizer.Speak(Prompt prompt)
   at EddiSpeechService.SpeechService.<>c__DisplayClass40_0.<speak>b__0()
2019-12-19T11:33:18 [Info] : Speech failed {"speech":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xml:lang=\"en-GB\"><break time=\"500ms\" /> left supercruise close to Surface Station, Black Hide.</speak>"}
2019-12-19T11:33:18 [Warning] ScriptResolver:resolveScript Failed to resolve this  script. System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.WhileNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.IfNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.SimpleDocument.Render(IStore store, TextWriter writer)
   at Cottle.Documents.AbstractDocument.Render(IStore store)
   at EddiSpeechResponder.ScriptResolver.resolveScript(String script, BuiltinStore store, Boolean master, Script scriptObject) 
2019-12-19T11:33:19 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID ac2a670f-e0a6-4312-9752-1a764c4f6001:System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Eddi.EDDI.<passToMonitorPostHandlersAsync>d__156.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Eddi.EDDI.<OnEvent>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() 
2019-12-19T11:33:19 [Info] EDDI:Stop EDDI 3.5.1 stopped 
```

**Comment by richardbuckle** [comment]
System.OutOfMemoryException. Not seen that in a while.

>
