### ISSUE TITLE
Carrier Jump has caused voiceattack to stop running

### ISSUE THREAD

**Issue by sharkysi** [EDCD/EDDI#1819]
## EDDI version in which issue is found
3.5.3.B3

## VoiceAttack version in which issue is found (as applicable)
1.8.5.0
## Steps to reproduce
Request carrier jump in Elite.  after a few seconds Voice attack closed, now when I start up voiceattack it shutsdown after initializing the EDDI plugin.

## Expected
To stay open

## Observed
Happens all the time now

## Investigation
a fault file is generated with an EDDI plugin error for the carrier jump request
[VoiceAttackFault.txt](https://github.com/EDCD/EDDI/files/4770514/VoiceAttackFault.txt)

**Comment by Tkael** [comment]
Thanks for the report. I'd like to review the original event. It looks like an expected value in the event may not be present (for the name of the nearest body).

```
Newtonsoft.Json.JsonSerializationException: Error getting value from 'shortname' on 'EddiEvents.CarrierJumpRequestEvent'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiEvents.CarrierJumpRequestEvent.get_shortname()
   at Getshortname(Object )
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Eddi.EDDI.eventHandler(Event event)
   at Eddi.EDDI.dequeueEvent()
   at Eddi.EDDI.<enqueueEvent>b__135_0()
```

Can you retrieve a copy of the journal file that's causing this issue? It should be located at [your Saved Games folder]/Frontier Developments/Elite Dangerous. If this happens each time that EDDI opens then it should be the .log file that was most recently modified.

As far as a temporary fix to this issue is concerned (if it happens each time EDDI starts)...
1. Please start Elite and log into the game (with EDDI closed). This will create a fresh journal .log file.
2. You should now be free to open EDDI. The issue shouldn't recur until a fresh CarrierJumpRequest event is written with similar parameters (and in the meantime we'll work to resolve that).

**Comment by sharkysi** [comment]
I removed the event to get round it, but backed it up (see attached)
[Journal.200612111845.01.log](https://github.com/EDCD/EDDI/files/4771630/Journal.200612111845.01.log)

**Comment by Tkael** [comment]
Thanks. This looks like an FDev bug... the `Body` property is missing from the event, even though there clearly should be something there because we have a `BodyID`. 
```json
{ "timestamp":"2020-06-12T11:01:40Z", "event":"CarrierJumpRequest", "CarrierID":3701442048, "SystemName":"Col 285 Sector GI-I a39-3", "SystemAddress":58117886593928, "BodyID":6 }
```

We can work around it now that we know about it.

**Comment by Tkael** [comment]
Have you noticed this same issue for other carrier jump requests? Or is it something that only rarely occurs? And you you mind if I share the .log file with FDev via their issue tracker?

**Comment by sharkysi** [comment]
That was my first carrier jump, will be trying one later so will see if the same thing happens again :)

**Comment by Tkael** [comment]
I've create an issue in Frontier's Issue Tracker to request a bug fix for this. If you've experienced this issue, please add a contribution / replication to the issue ticket. https://issues.frontierstore.net/issue-detail/16792
