### ISSUE TITLE
Error with Signal detected script: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1935]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A	

## Steps to reproduce
1. EDDI says the below ERROR  after entering certain system(s).  In this case,  GCRV 1568

## Expected
No errors with script execution

## Observed
```
Destination confirmed. MFS tabula rasa is in transit to the G C R V 1 5 6 8 system. G C R V 1 5 6 8 is an independent Cooperative of well over 377 million souls, and is aligned to Li Yong Rui. Aseveljet is the immediate faction. There are 116 orbital stations and 10 planetary stations in this system. Current location is over 109 lightyears from home.

Information:  The Future of Lan Gundi faction is recovering after losing a War with the Silver Bridge PLC faction for control of Gagnan Hub.  The Independents of G C R V 1 5 6 8 and Aseveljet are undergoing a boom   You have 1 depot mission at Ocellus Starport, Cernan Dock.

Error with Signal detected script: Collection was modified; enumeration operation may not execute.
```

## Investigation
Does not appear to occur with `Signal Detected` script unchecked. 
[attachments.zip](https://github.com/EDCD/EDDI/files/5048562/attachments.zip)

Appears to occur because system signals are being accessed from a collection which is not thread safe.

**Comment by Tkael** [comment]
```
2020-10-19T09:07:04 [Warning] ScriptResolver:resolveFromValue Collection was modified; enumeration operation may not execute. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Cottle.Values.ReflectionValue.Resolve()
   at Cottle.Values.ResolveValue.Acquire()
   at Cottle.Values.ResolveValue.get_Type()
   at Cottle.Builtins.BuiltinFunctions.<>c.<.cctor>b__47_13(IList`1 values)
   at Cottle.Functions.NativeFunction.<>c__DisplayClass13_0.<.ctor>b__0(IList`1 v, IStore s, TextWriter o)
   at Cottle.Functions.NativeFunction.Execute(IList`1 arguments, IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.IfNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.SimpleDocument.Render(IStore store, TextWriter writer)
   at Cottle.Documents.AbstractDocument.Render(IStore store)
   at EddiSpeechResponder.ScriptResolver.resolveFromValue(String script, BuiltinStore store, Boolean isTopLevelScript, Script scriptObject)
```
Appears to be a threading error caused by trying to access system signals via the Cottle script while system signals are being modified (particularly in systems with many fleet carriers).
