### ISSUE TITLE
EDDI crashes in certain systems

### ISSUE THREAD

**Issue by Thyast** [EDCD/EDDI#1950]
[##] EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.6

## Steps to reproduce
Go to Djiwal or Maia

## Observed
The system arrival scripts runs and then VA crashes. I did not do anything in between. 

## Investigation
Does not happen if EDDI is disabled. So it comes from EDDI.
Verbose logs attached which shows an exception: [eddi.log](https://github.com/EDCD/EDDI/files/5121626/eddi.log)

**Comment by Tkael** [comment]
Hmm. Haven't seen one like this before.
```
2020-08-25T05:35:28 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID 52004055-19b8-4027-b2a9-294765640900:System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.ComponentModel.AsyncOperation.Post(SendOrPostCallback d, Object arg)
   at System.Speech.Internal.AsyncSerializedWorker.OnWorkItemPending()
   at System.Speech.Internal.AsyncSerializedWorker.AddItem(AsyncWorkItem item)
   at System.Speech.Recognition.RecognizerBase.FireAudioLevelUpdatedEvent(Int32 audioLevel)
   at System.Speech.Recognition.RecognizerBase.DispatchEvents(Object eventData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Speech.Internal.AsyncSerializedWorker.WorkerProc(Object ignored)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() 
```

Does it happen all of the time or just some of the time?
Does EDDI crash if you run EDDI in standalone mode (without VoiceAttack)?

**Comment by Tkael** [comment]
Also, have you looked at VoiceAttackFault.txt in VoiceAttack's root installation directory? Maybe that will provide some additional clues.

**Comment by Tkael** [comment]
I wasn't able to replicate this issue this evening. I visited both Maia and Djiwal this evening, dropping out of supercruise shortly after arrival (trying to match the conditions logged).

Does this occur when you are using the default EDDI profile for VoiceAttack or only when you are using your own profile? Likewise for EDDI's default personality vs. your customized personality?

**Comment by Thyast** [comment]
Thanks for helping.
It happens after a few seconds or minutes each time I restart VA.
I only use EDDI's defaut personality.
I will try with EDDI standalone to check.
I checked VA fault and I saw that which seems to be the same as in EDDI's log I sent:
`8/25/2020 7:35:27 AM***************************************************************************************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.ComponentModel.AsyncOperation.Post(SendOrPostCallback d, Object arg)
   at System.Speech.Internal.AsyncSerializedWorker.OnWorkItemPending()
   at System.Speech.Internal.AsyncSerializedWorker.AddItem(AsyncWorkItem item)
   at System.Speech.Recognition.RecognizerBase.FireAudioLevelUpdatedEvent(Int32 audioLevel)
   at System.Speech.Recognition.RecognizerBase.DispatchEvents(Object eventData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Speech.Internal.AsyncSerializedWorker.WorkerProc(Object ignored)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
***VoiceAttack v1.8.6 - Windows 10.0.18363.0
Plugin assemblies:
EDDI 3.7.0 [EddiVoiceAttackResponder.dll] (enabled) - Last call: 25 Aug 2020 07:31:07:40 VA_Invoke1
`

**Comment by Tkael** [comment]
The data seems to be pointing towards `VA_Invoke1`, the method called when a command is sent to EDDI though the plugin interface. 

Do you have any VoiceAttack commands that trigger off of the `Music` or `Entered normal space` events?

**Comment by Thyast** [comment]
I played in standalone mode and it crashed too. Nothing special in the log as far as I can see. The exception doesn't show up. I think it was more a consequence than a cause.
[eddi.log](https://github.com/EDCD/EDDI/files/5131206/eddi.log)
And to answer your question, I don't have such commands. But as said, it also happens in standalone.
I've played the whole night yesterday in another system without any problem.
I've tried to go back to Djiwal today and it crashed when I dropped at the nav beacon. I tried to scan it and it crashed around that time. I don't know if it was before or after.
Edit: I stopped playing then restarted at the nav beacon which I left quickly going to supercruise after maybe one or two ship scans and it crashed again. Not sure when exactly.

**Comment by Tkael** [comment]
Are you sure that you provided the right log file? The log file you attached from your standalone session only covers about one minute from when EDDI starts to when EDDI ends and does not include any exceptions / evidence of a crash (though it does log a graceful stop). In the %appdata%/EDDI folder, you'll find up to ten files with the `.log` from the current and prior recent EDDI runs.

I jumped into the nav beacon at Djiwal this evening, scanned the nav beacon, and stuck around for a while but no crash occurred.

Can you describe (or perhaps link a video to show) exactly what you observe when a crash does occur (preferably in standalone mode)?

**Comment by Tkael** [comment]
Hello @Thyast, is this still occurring? Do you have any more details that might help us to replicate it?
Thanks!

**Comment by Thyast** [comment]
Hello @Tkael, yes it is. It happened again in some random systems. One with an engineer, but I don't remember which one.
I hadn't much time to spend investigating on this.
There is not much more to say on my side. I use EDDI normaly and the minute after it does not run anymore. I could not find out the origin of the crash.
I think having more logs could help locating the crash origin. I can run a debug version if you want and tell me what to do.

**Comment by Tkael** [comment]
If the standard log isn't recording any exception then EDDI isn't behaving like a crash is occurring.  A verbose debug log would provide additional context but that context is unlikely to be helpful if the crash isn't traceable to some exception in the code.

Is it possible that some other application on your system is sending a command that is simply closing EDDI?

**Comment by Thyast** [comment]
I think in that case it would happen in any system. Or it would be caused by an ED related app which would have the knowledge of the system I'm in. But I don't use another app of that kind beside VA+EDDI.
It happens only in certain systems. And multiple times when it happens.

**Comment by Tkael** [comment]
I visited both of the original systems but was unable to replicate a crash of any sort so if it's linked to those systems it must be a property which is transient.

The fact that you are describing a crash occurring repeatedly in the same system suggests that some exception should be appearing in the logs. Next time this occurs, please zip up all ten .log files and attach them here for review?

You still haven't described exactly what you observe when EDDI crashes. Does the application just silently stop? Does it freeze? Is a message box or voice message triggered?

**Comment by Tkael** [comment]
Closing due to inability to replicate and insufficient detail as to the nature of the crash. If you respond, we can re-open the ticket. o7
