### ISSUE TITLE
Corrupted shipmonitor.json

### ISSUE THREAD

**Issue by sunnie2** [EDCD/EDDI#305]
## EDDI version in which issue found
2.4.6-b1

## Steps to reproduce

1. Unknown : Files requested by Tkael

## Expected
Fuel tank level reporting to match actual.

## Observed
Always stated that fuel tank was empty or less than 25% in Imperial Cutter

## Investigation
Clearing shipmonitor.json resolved misreporting, sending on file and log as requested.
[shipmonitor.zip](https://github.com/EDCD/EDDI/files/1558073/shipmonitor.zip)
[eddi.log](https://github.com/EDCD/EDDI/files/1558083/eddi.log)

**Comment by Tkael** [comment]
Thanks cmdr. :-)

**Comment by Tkael** [comment]
Ok. So according to your ship monitor, your current ship ID was 22, but there was no ship with an ID of 22 in your shipmonitor. Thus, EDDI had no idea what ship you were actually in. It's not clear yet how your shipmonitor became corrupted and either failed to write or removed your cutter, but we have the data and hopefully we'll be able to figure it out.

**Comment by Tkael** [comment]
I see that your reporting this issue again. Would you please send a new copy of your shipmonitor.json and log to re-review?

**Comment by sunnie2** [comment]
Will do!

**Comment by Tkael** [comment]
Logging your comment on how we might replicate this error: 
```
It seems that currently, when you purchase a new ship anywhere, change the name, equip it and take her out, the ship reports the tanks at Zero, assuming because of the corrupted json.
```

**Comment by Tkael** [comment]
Finding: EDDI is attempting to write the ship configuration before the asynchronous operations to add and remove ships have been completed. Thus, the newly added ships aren't being written to the shipyard correctly.
I'll add some code to so that EDDI waits to write the shipyard until those asynchronous add and remove operations are completed.

**Comment by Tkael** [comment]
Closed pending approval of PR #311.

**Comment by Tkael** [comment]
Reopening. Not resolved by the final version of PR #311.

**Comment by richardbuckle** [comment]
Speculative fix in 3.0b1, let's re-test.

**Comment by Tkael** [comment]
Unfortunately, the speculative fix does not appear to have worked. 
```System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at EddiShipMonitor.ShipMonitor._RemoveShip(Nullable`1 localid) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 924
   at EddiShipMonitor.ShipMonitor.<>c__DisplayClass55_0.<RemoveShip>b__0(Object _) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 906
   at System.Threading.SynchronizationContext.Send(SendOrPostCallback d, Object state)
   at EddiShipMonitor.ShipMonitor.RemoveShip(Nullable`1 localid) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 906
   at EddiShipMonitor.ShipMonitor._AddShip(Ship ship) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 890
   at EddiShipMonitor.ShipMonitor.<>c__DisplayClass53_0.<AddShip>b__0(Object _) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 878
   at System.Threading.SynchronizationContext.Send(SendOrPostCallback d, Object state)
   at EddiShipMonitor.ShipMonitor.AddShip(Ship ship) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 878
   at EddiShipMonitor.ShipMonitor.handleShipLoadoutEvent(ShipLoadoutEvent event) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 437
   at EddiShipMonitor.ShipMonitor.PreHandle(Event event) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 127
   at Eddi.EDDI.OnEvent(Event event) in C:\Users\[User]\source\repos\EDDI\EDDI\EDDI.cs:line 754
2018-03-02T07:26:35 EDDI:refreshProfile [W] Monitor failed System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at EddiShipMonitor.ShipMonitor._AddShip(Ship ship) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 891
   at EddiShipMonitor.ShipMonitor.<>c__DisplayClass53_0.<AddShip>b__0(Object _) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 878
   at System.Threading.SynchronizationContext.Send(SendOrPostCallback d, Object state)
   at EddiShipMonitor.ShipMonitor.AddShip(Ship ship) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 878
   at EddiShipMonitor.ShipMonitor.HandleProfile(JObject profile) in C:\Users\[User]\source\repos\EDDI\ShipMonitor\ShipMonitor.cs:line 817
   at Eddi.EDDI.<>c__DisplayClass135_1.<refreshProfile>b__2() in C:\Users\[User]\source\repos\EDDI\EDDI\EDDI.cs:line 1547
```

**Comment by Djuwanna** [comment]
I'm having the same problem - I deleted the section of the script for fuel reporting <25 and now I'm getting accurate fuel responses from the other parts?!
