### ISSUE TITLE
new ship does not show up on edsm

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/EDDI#398]
## EDDI version in which issue found
v2.4.6-b2 and v3.0.0-b1

## Steps to reproduce

1. buy a new ship
2. check on edsm

## Expected
new ship shown

## Observed
new ship shown nto shown

## Investigation
- delete shipmon.json (in both versions)
- merge new ship with ships from old json file
- check json syntax
- all ships are shown in eddi (ship monitor) und corolis links works for all ships
- new ship ist also announce by eddi voice actions and ist properly filled in va variable
- all others informations like current credits are updated on edsm

**Comment by Tkael** [comment]
Wait, you're manually adding the new ship to the json file (e.g. not through EDDI)? Please clarify?

**Comment by lwt-pressy** [comment]
no, I delete the json file and let eddi make a new file. There will be all ships, but the old ship are without details (compartments), so no corolis link.  Then I cut out the old ships from the previously saved file and merge it in the new file by replacing the old ships. Thats the only way I get all Ships with details. That procedure I had to do in 2.2.4 after each buy. Otherwise I had to jump all over the Galaxy do use the ships once for getting my details back.

Nevertheless, for the test I used a newly generated file (by eddi) and jump at least two times, but the ship never showed up in edsm (only in eddi).

**Comment by Tkael** [comment]
Ah. The ship details are sent during the "Loadout" event (which is incidentally the same event that adds the detailed info you are currently manually adding to the ship). EDDI won't realize that you've manually edited the file so without a loadout event it won't send updated data.

**Comment by Tkael** [comment]
Closing this issue as invalid / not the designed use. That said, I'll still be monitoring this conversation if you have any further questions.

**Comment by lwt-pressy** [comment]
As I described this was this was done after the error ocurred, so how can something done after the error occurred, trying to fix it make the error invalid?

**Comment by Tkael** [comment]
Trying to manually work around the error described by #305 by cutting together old and new data simply won't work and will result in issues like the one we are now discussing - EDDI wasn't designed to detect manual alterations to the shipmonitor and wasn't designed to resend data if those files are manually altered.

**Comment by lwt-pressy** [comment]
Even if I 

1.  stop VA (EDDI plugin) 
2. delete the shipmon.json 
3. restart VA 

the current ship does not show up in EDSM after playing for a day. Perhaps related to this entry in eddi.log (occurs multiple times):

> 2018-03-03T21:56:37 JournalMonitor:ParseJournalEntry [W] Failed to parse line: System.ArgumentException: Unparseable value for Value
   at Utilities.JsonParsing.getLong(String key, Object val)
   at Utilities.JsonParsing.getLong(IDictionary`2 data, String key)
   at EddiJournalMonitor.JournalMonitor.ParseJournalEntry(String line) 
2018-03-03T21:56:37 JournalMonitor:ParseJournalEntry [E] Exception whilst parsing line { "timestamp":"2018-03-03T21:56:37Z", "event":"Loadout", "Ship":"Anaconda", "ShipID":9, "ShipName":"LWT Stardust", "ShipIdent":"PRES06", "HullValue":170267329, "ModulesValue":25056664, "Rebuy":9766202, "Modules":[ { "Slot":"HugeHardpoint1", "Item":"Hpt_MultiCannon_Gimbal_Large", "On":true, "Priority":0, "AmmoInClip":90, "AmmoInHopper":2100, "Health":1.000000, "Value":578436 }, { "Slot":"LargeHardpoint1", "Item":"Hpt_MultiCannon_Gimbal_Large", "On":true, "Priority":0, "AmmoInClip":90, "AmmoInHopper":2100, "Health":1.000000, "Value":578436 }, { "Slot":"LargeHardpoint2", "Item":"Hpt_PulseLaser_Turret_Large", "On":true, "Priority":0, "Health":1.000000, "Value":400400 }, { "Slot":"LargeHardpoint3", "Item":"Hpt_PulseLaser_Turret_Large", "On":true, "Priority":0, "Health":1.000000, "Value":400400 }, { "Slot":"MediumHardpoint1", "Item":"Hpt_MiningLaser_Fixed_Medium", "On":true, "Priority":0, "Health":1.000000, "Value":27091 }, { "Slot":"MediumHardpoint2", "Item":"Hpt_MiningLaser_Fixed_Medium", "On":true, "Priority":0, "Health":1.000000, "Value":27091 }, { "Slot":"SmallHardpoint1", "Item":"Hpt_PulseLaser_Gimbal_Small", "On":true, "Priority":0, "Health":1.000000, "Value":7920 }, { "Slot":"SmallHardpoint2", "Item":"Hpt_PulseLaser_Gimbal_Small", "On":true, "Priority":0, "Health":1.000000, "Value":7920 }, { "Slot":"TinyHardpoint1", "Item":"Hpt_PlasmaPointDefence_Turret_Tiny", "On":true, "Priority":0, "AmmoInClip":12, "AmmoInHopper":10000, "Health":1.000000, "Value":22255 }, { "Slot":"TinyHardpoint2", "Item":"Hpt_PlasmaPointDefence_Turret_Tiny", "On":true, "Priority":0, "AmmoInClip":12, "AmmoInHopper":10000, "Health":1.000000, "Value":22255 }, { "Slot":"TinyHardpoint3", "Item":"Hpt_PlasmaPointDefence_Turret_Tiny", "On":true, "Priority":0, "AmmoInClip":12, "AmmoInHopper":10000, "Health":1.000000, "Value":22255 }, { "Slot":"TinyHardpoint4", "Item":"Hpt_PlasmaPointDefence_Turret_Tiny", "On":true, "Priority":0, "AmmoInClip":12, "AmmoInHopper":10000, "Health":1.000000, "Value":22255 }, { "Slot":"TinyHardpoint5", "Item":"Hpt_ShieldBooster_Size0_Class5", "On":true, "Priority":0, "Health":1.000000, "Value":281000 }, { "Slot":"TinyHardpoint6", "Item":"Hpt_ShieldBooster_Size0_Class5", "On":true, "Priority":0, "Health":1.000000, "Value":281000 }, { "Slot":"TinyHardpoint7", "Item":"Hpt_PlasmaPointDefence_Turret_Tiny", "On":true, "Priority":0, "AmmoInClip":12, "AmmoInHopper":10000, "Health":1.000000, "Value":22255 }, { "Slot":"TinyHardpoint8", "Item":"Hpt_PlasmaPointDefence_Turret_Tiny", "On":true, "Priority":0, "AmmoInClip":12, "AmmoInHopper":10000, "Health":1.000000, "Value":22255 }, { "Slot":"Armour", "Item":"Anaconda_Armour_Grade1", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"PaintJob", "Item":"PaintJob_Anaconda_Vibrant_Red", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"PowerPlant", "Item":"Int_Powerplant_Size8_Class2", "On":true, "Priority":1, "Health":1.000000, "Value":6021722 }, { "Slot":"MainEngines", "Item":"Int_Engine_Size7_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":1899597 }, { "Slot":"FrameShiftDrive", "Item":"Int_Hyperdrive_Size6_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":599242 }, { "Slot":"LifeSupport", "Item":"Int_LifeSupport_Size5_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":79444 }, { "Slot":"PowerDistributor", "Item":"Int_PowerDistributor_Size8_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":1743961 }, { "Slot":"Radar", "Item":"Int_Sensors_Size8_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":1743961 }, { "Slot":"FuelTank", "Item":"Int_FuelTank_Size5_Class3", "On":true, "Priority":1, "Health":1.000000, "Value":117304 }, { "Slot":"Decal1", "Item":"Decal_Explorer_Starblazer", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"Decal2", "Item":"Decal_Explorer_Starblazer", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"Decal3", "Item":"Decal_Explorer_Starblazer", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipName0", "Item":"Nameplate_Practical02_White", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipName1", "Item":"Nameplate_Practical02_White", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipID0", "Item":"Nameplate_ShipID_DoubleLine_White", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipID1", "Item":"Nameplate_ShipID_DoubleLine_White", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"Slot01_Size7", "Item":"Int_CargoRack_Size7_Class1", "On":true, "Priority":1, "Health":1.000000, "Value":1178420 }, { "Slot":"Slot02_Size6", "Item":"Int_CargoRack_Size6_Class1", "On":true, "Priority":1, "Health":1.000000, "Value":362591 }, { "Slot":"Slot03_Size6", "Item":"Int_CargoRack_Size6_Class1", "On":true, "Priority":1, "Health":1.000000, "Value":435109 }, { "Slot":"Slot04_Size6", "Item":"Int_ShieldGenerator_Size5_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":189035 }, { "Slot":"Slot05_Size5", "Item":"Int_DroneControl_Collection_Size5_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":97200 }, { "Slot":"Slot06_Size5", "Item":"Int_DroneControl_Collection_Size5_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":116640 }, { "Slot":"Slot07_Size5", "Item":"Int_DroneControl_Prospector_Size5_Class2", "On":true, "Priority":0, "Health":1.000000, "Value":97200 }, { "Slot":"Slot08_Size4", "Item":"Int_Refinery_Size4_Class5", "On":true, "Priority":0, "Health":1.000000, "Value":5401015 }, { "Slot":"Slot09_Size4", "Item":"Int_DockingComputer_Standard", "On":true, "Priority":0, "Health":1.000000, "Value":5400 }, { "Slot":"Slot10_Size4", "Item":"Int_StellarBodyDiscoveryScanner_Advanced", "On":true, "Priority":1, "Health":1.000000, "Value":1545000 }, { "Slot":"Slot13_Size2", "Item":"Int_DetailedSurfaceScanner_Tiny", "On":true, "Priority":1, "Health":1.000000, "Value":250000 }, { "Slot":"Military01", "Item":"Int_ModuleReinforcement_Size5_Class2", "On":true, "Priority":1, "Health":1.000000, "Value":450000 }, { "Slot":"PlanetaryApproachSuite", "Item":"Int_PlanetApproachSuite", "On":true, "Priority":1, "Health":1.000000, "Value":599 }, { "Slot":"VesselVoice", "Item":"VoicePack_Verity", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"ShipCockpit", "Item":"Anaconda_Cockpit", "On":true, "Priority":1, "Health":1.000000 }, { "Slot":"CargoHatch", "Item":"ModularCargoBayDoor", "On":true, "Priority":2, "Health":1.000000 } ] }
