### ISSUE TITLE
Error in log when recreating shipmonitor.json

### ISSUE THREAD

**Issue by moreyummystuff** [EDCD/EDDI#408]
## EDDI version in which issue found
3.0.0-b1

## Steps to reproduce

1. Delete shipmonitor.json
2. Start EDDI

## Observed 

Error in log file:

2018-03-08T15:33:55 EDDI:refreshProfile [W] Monitor failed System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at EddiShipMonitor.ShipMonitor._AddShip(Ship ship)
   at EddiShipMonitor.ShipMonitor.<>c__DisplayClass53_0.<AddShip>b__0(Object _)
   at System.Threading.SynchronizationContext.Send(SendOrPostCallback d, Object state)
   at EddiShipMonitor.ShipMonitor.AddShip(Ship ship)
   at EddiShipMonitor.ShipMonitor.HandleProfile(JObject profile)
   at Eddi.EDDI.<>c__DisplayClass135_1.<refreshProfile>b__2()

## Investigation
The ship list is not complete, more ships are added with each subsequent EDDI restart.

**Comment by Tkael** [comment]
Thanks for reporting, but this is already a known issue. Ref. #305. Closing as a duplicate.
