### ISSUE TITLE
Exception thrown during Frontier API refreshes of the shipyard.

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#421]
## EDDI version in which issue found
In VoiceAttack, 3.0.0-b2 dev build

## Observed
EDDI:refreshProfile [W] Monitor failed System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at EddiShipMonitor.ShipMonitor.HandleProfile(JObject profile) in C:\Users\Ken\Source\Repos\EDDI\ShipMonitor\ShipMonitor.cs:line 790
   at Eddi.EDDI.<>c__DisplayClass126_1.<refreshProfile>b__2() in C:\Users\Ken\Source\Repos\EDDI\EDDI\EDDI.cs:line 1467

**Comment by richardbuckle** [comment]
Steps to reproduce?

**Comment by richardbuckle** [comment]
Oh wait I see it. Care is required removing an object from a collection that you're iterating over. (Think of the cartoon character sawing off the branch he is standing on.)
