### ISSUE TITLE
'ModuleSwap' Event: Add

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#43]
Needs to update the ship compartment object?

**Comment by Syrrianyl** [comment]
my work is only in draft form for this event (and also oyher 'Module' events).  I think it would  be wise to apply json file to save the list of the differents compartments and the places of storage (a ModulesMonitor?)
But for now, I do not feel at ease with these "monitors" (how to create and use)

**Comment by Tkael** [comment]
@Hoodathunk is studying this.

**Comment by Hoodathunk** [comment]
The ShipMonitor handles tracking of all modules (Core internal, hard points, and compartments) and associated slots. EDDI 2.3.0 only updates module data for the active ship during cAPI Profile refreshes.

jgm intended to the associated during module 'purchased', retrieved', 'sold', 'stored' and 'swapped' events but didn't get around to it before his 'departure'.

I have written and pushed the individual event classes, modified the JournalMonitor to service the events, and placed 'todo' methods into the ShipMonitor for updating the ship module databases. eddi.json has been updated with default, empty scripts.

I've pushed the module events to github to 'parallel path' testing of the module events with the Speech & VoiceAttack Responders while continuing work on the ShipMonitor.

**Comment by Tkael** [comment]
Event added. Ship compartment object shall be updated under issue https://github.com/EDCD/EDDI/issues/37

**Comment by Hoodathunk** [comment]
Completed.

**Comment by Tkael** [comment]
This event is throwing an exception:
```
2017-09-20T02:58:28 EDDI:OnEvent [E] {"ship":"diamondbackxl","shipid":38,"fromslot":"MediumHardpoint1","frommodule":{"name":"Mining Laser","class":2,"grade":"D","value":22580,"ShipId":null,"mount":0,"clipcapacity":null,"hoppercapacity":null,"price":0,"enabled":false,"priority":0,"health":0.0,"modified":false,"EDID":0,"EDName":"Hpt_MiningLaser_Fixed_Medium","EDDBID":889},"toslot":"MediumHardpoint2","tomodule":{"name":"Multi-Cannon","class":2,"grade":"F","value":57000,"ShipId":null,"mount":1,"clipcapacity":0,"hoppercapacity":2100,"price":0,"enabled":false,"priority":0,"health":0.0,"modified":false,"EDID":0,"EDName":"Hpt_MultiCannon_Gimbal_Medium","EDDBID":870},"raw":"{ \"timestamp\":\"2017-09-20T02:58:28Z\", \"event\":\"ModuleSwap\", \"FromSlot\":\"MediumHardpoint1\", \"ToSlot\":\"MediumHardpoint2\", \"FromItem\":\"$hpt_mininglaser_fixed_medium_name;\", \"FromItem_Localised\":\"Mining Laser\", \"ToItem\":\"$hpt_multicannon_gimbal_medium_name;\", \"ToItem_Localised\":\"Multi-Cannon\", \"Ship\":\"diamondbackxl\", \"ShipID\":38 }","timestamp":"2017-09-20T02:58:28Z","type":"Module swapped"} System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EddiShipMonitor.ShipMonitor.handleModuleSwappedEvent(ModuleSwappedEvent event)
   at EddiShipMonitor.ShipMonitor.PreHandle(Event event)
   at Eddi.EDDI.OnEvent(Event event)
```
Here's the corresponding raw journal entry:
`{ "timestamp":"2017-09-20T02:58:28Z", "event":"ModuleSwap", "FromSlot":"MediumHardpoint1", "ToSlot":"MediumHardpoint2", "FromItem":"$hpt_mininglaser_fixed_medium_name;", "FromItem_Localised":"Mining Laser", "ToItem":"$hpt_multicannon_gimbal_medium_name;", "ToItem_Localised":"Multi-Cannon", "Ship":"diamondbackxl", "ShipID":38 }`
It looks like ShipID is present in the raw journal entry, is being recognized at the top level, but is not being filled / passed correctly to the lower levels of the event code.

**Comment by Hoodathunk** [comment]
Fixed. No thrown exceptions and compartments/hardpoints ship objects properly updating in-game.
