### ISSUE TITLE
EDDI Core: Limpets not handled correctly

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#52]
Clipped from EDDI.log entries during a beta test:
```
2017-09-03T21:36:10 EDDI:OnEvent [E] {"inventory":[],"raw":"{ \"timestamp\":\"2017-09-03T21:36:10Z\", \"event\":\"Cargo\", \"Inventory\":[  ] }","timestamp":"2017-09-03T14:36:10.513849-07:00","type":"Cargo inventory"} System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiShipMonitor.ShipMonitor.handleCargoInventoryEvent(CargoInventoryEvent event) in C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\ShipMonitor\ShipMonitor.cs:line 499
   at EddiShipMonitor.ShipMonitor.PreHandle(Event event) in C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\ShipMonitor\ShipMonitor.cs:line 143
   at Eddi.EDDI.OnEvent(Event event) in C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\EDDI\EDDI.cs:line 762
2017-09-03T21:36:10 VoiceAttackPlugin:VA_Init1 [I] Executed command ((EDDI commander continued)) 
```
```
2017-09-03T21:41:49 EDDI:OnEvent [E] {"amount":20,"price":101,"raw":"{ \"timestamp\":\"2017-09-03T21:41:49Z\", \"event\":\"BuyDrones\", \"Type\":\"Drones\", \"Count\":20, \"BuyPrice\":101, \"TotalCost\":2020 }","timestamp":"2017-09-03T21:41:49Z","type":"Limpet purchased"} System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiShipMonitor.ShipMonitor.handleLimpetPurchasedEvent(LimpetPurchasedEvent event) in C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\ShipMonitor\ShipMonitor.cs:line 504
   at EddiShipMonitor.ShipMonitor.PreHandle(Event event) in C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\ShipMonitor\ShipMonitor.cs:line 147
   at Eddi.EDDI.OnEvent(Event event) in C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\EDDI\EDDI.cs:line 762
2017-09-03T21:41:49 VoiceAttackPlugin:VA_Init1 [I] Executed command ((EDDI limpet purchased)) 
```

**Comment by Tkael** [comment]
No more exceptions are can be found as of this writing (now that the connection to the Frontier API has been restored and is being repaired). Closing this issue as resolved.

**Comment by Tkael** [comment]
Though the exceptions are no longer present, cargo still does not seem to be getting written correctly. 
When carrying cargo, the following should give the name of the cargo, but is empty:
```
{for cargo in ship.cargo:
      {cargo.commodity.name}
}
```

**Comment by Tkael** [comment]
On hold until we get a way to track when limpets are used.

**Comment by Tkael** [comment]
Incorporated.
