### ISSUE TITLE
Near surface event exception

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#614]
## EDDI version in which issue found
3.0.1-b4

## Steps to reproduce

Visit engineers.

## Expected
No exceptions, data handled appropriately.

## Observed
```cs
2018-05-30T06:28:33 EDDI:eventHandler [E] Failed to handle event {"approaching_surface":true,"system":"Wolf 397","body":"Trus Madi","raw":"{ \"timestamp\":\"2018-05-30T06:28:34Z\", \"event\":\"ApproachBody\", \"StarSystem\":\"Wolf 397\", \"SystemAddress\":3107576681170, \"Body\":\"Trus Madi\", \"BodyID\":7 }","timestamp":"2018-05-30T06:28:34Z","type":"Near surface"} System.NullReferenceException: Object reference not set to an instance of an object.
   at Eddi.EDDI.eventNearSurface(NearSurfaceEvent theEvent) in EDDI\EDDI.cs:line 1326
   at Eddi.EDDI.eventHandler(Event event) in EDDI\EDDI.cs:line 679
2018-05-30T06:29:12 EDDI:eventHandler [E] Failed to handle event {"system":"Wolf 397","bodytype":"Planet","body":"Trus Madi","raw":"{ \"timestamp\":\"2018-05-30T06:29:12Z\", \"event\":\"SupercruiseExit\", \"StarSystem\":\"Wolf 397\", \"SystemAddress\":3107576681170, \"Body\":\"Trus Madi\", \"BodyID\":7, \"BodyType\":\"Planet\" }","timestamp":"2018-05-30T06:29:12Z","type":"Entered normal space"} System.NullReferenceException: Object reference not set to an instance of an object.
   at Eddi.EDDI.eventEnteredNormalSpace(EnteredNormalSpaceEvent theEvent) in EDDI\EDDI.cs:line 1141
   at Eddi.EDDI.eventHandler(Event event) in EDDI\EDDI.cs:line 599
```

**Comment by richardbuckle** [comment]
PR merged.
