### ISSUE TITLE
Commodity sale check script broken: `source` is null

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#623]
## EDDI version in which issue found
3.0.1-b4

## Steps to reproduce

1. Open the editor for the "Commodity sale check" script and click the Test button. Or trigger it by docking.

## Expected
Normal operation of the script.

## Observed
```
There is a problem with the: Commodity sale check script. Value cannot be null.
Parameter name: source
```

## Investigation
Still looking into it.

**Comment by richardbuckle** [comment]
OK this one is my screw-up. Will fix.

**Comment by richardbuckle** [comment]
Log output:
```
2018-06-07T16:40:55 ScriptResolver:resolveScript [W] Failed to resolve the: Commodity sale check script. System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EddiSpeechResponder.ScriptResolver.<>c.<buildStore>b__13_35(IList`1 values) in C:\dev\EDDI\SpeechResponder\ScriptResolver.cs:line 653
   at Cottle.Functions.NativeFunction.<>c__DisplayClass13_0.<.ctor>b__0(IList`1 v, IStore s, TextWriter o)
   at Cottle.Functions.NativeFunction.Execute(IList`1 arguments, IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.AssignNodes.ValueAssignNode.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.AssignNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.IfNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.ForNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.SimpleDocument.Render(IStore store, TextWriter writer)
   at Cottle.Documents.AbstractDocument.Render(IStore store)
   at EddiSpeechResponder.ScriptResolver.resolveScript(String script, BuiltinStore store, Boolean master, Script scriptObject) in C:\dev\EDDI\SpeechResponder\ScriptResolver.cs:line 86 
```

**Comment by Tkael** [comment]
Looks like an area of the code that I touched recently may be at least partially at fault?
In ScriptResolver.CS line 653, perhaps change...
```CS
result = station == null ? null : station.commodities.FirstOrDefault(c => c.definition.localizedName == values[0].AsString);
```
to
```CS
result = station?.commodities?.FirstOrDefault(c => c.definition?.localizedName == values[0].AsString);
```

**Comment by richardbuckle** [comment]
Yep, just about to give that a test.

**Comment by richardbuckle** [comment]
What was puzzling me was that there was nothing called `source` in the Cottle or the C#.

Turned out that the templated `FirstOrDefault()` method uses `source` to refer to the `this` object.

Headdesk.

**Comment by richardbuckle** [comment]
Fixed.
