### ISSUE TITLE
EDDI 3.0.1 rc1, 2 and 3 fail to launch

### ISSUE THREAD

**Issue by LuPoNe81** [EDCD/EDDI#718]
## EDDI version in which issue found
EDDI-3.0.1-rc3

## Steps to reproduce

1. I opened my working version of EDDI, 3.0.1-b4, it showed an updated so I clicked to do it, and nothing happened
2. Downloaded the latest release installer from the website
3. Update or install the program (either update or from scratch= in the default location
4. Click on the icon to launch

## Expected
EDDI Program opening without issues

## Observed
No sign, no error message, no EDDI window popping up, the process in the task manager lasts for a few seconds then disappears.

## Investigation
1. Tried to remove all the EDDI files related in %APPDATA%, but the issue persisted (the program re-created a few of the files
2. I tried EDDI-3.0.1-rc1 an rc2 without luck (deleting any remaining files in %appdata%, clean install), same results
3. Every other previous version up to EDDI-3.0.1-b4 work fine and without issues.

Reverted to EDDI-3.0.1-b4 for the time being.

Edit: please let me know what can I upload or what information I can give you to help you on this.

**Comment by lbeltrame** [comment]
This looks like a missing localization file.

The log says:

` Files:Read File D:\Games\EDDI\eddi.it.jsonb not found System.Collections.Generic.Dictionary`2[System.String,System.Object]`

**Comment by lbeltrame** [comment]
In fact, renaming eddi.it.json to eddi.it.jsonb makes EDDI start again.

**Comment by LuPoNe81** [comment]
Thanks for following up on this, I couldn't figure it out myself, and it seems odd that it forces to look for the Italian localization files, even though I've always used the program in english?

Will try the temporary fix just by copying the eddi.jsonb file and renaming it as eddb.it.jsonb

Thanks!

**Comment by LuPoNe81** [comment]
Update: there's no missing localization file, right upon install, it looks like the eddi.it.jsonb is already in the program folder:

![cattura](https://user-images.githubusercontent.com/40714861/42129507-6b00e69e-7cc6-11e8-96d2-b2d27ed97fdf.JPG)

So there's no fix yet, issue not resolved.

Where can I look for the logs to see if it traces something?

**Comment by Tkael** [comment]
Found and fixed I think. Thanks for the sleuthing. :-)

**Comment by LuPoNe81** [comment]
You're welcome, thanks to you for all the amazin work you're doing on this!

**Comment by Lathomere** [comment]
Aloha,  and apologies for asking a question here, but I'm having the same issue.  I've uninstalled as well, and reinstalled the latest rc version, but can't seem to get it to fire off.  Attempted, no doubt poorly, to do the above rename fix, but I'm certainly no coder and it hasn't done the trick.  

Any help would be greatly appreciated.  I miss my robot wife giving me directions to a parking spot...

Lath

**Comment by LuPoNe81** [comment]
@Lathomere probably for you it's another of the files. the .it. one is for the Italian localization. Try with another one and test, then post your results :)

**Comment by Lathomere** [comment]
Aloha,  and apologies for asking a question here, but I'm having the same issue.  I've uninstalled as well, and reinstalled the latest rc version, but can't seem to get it to fire off.  Attempted, no doubt poorly, to do the above rename fix, but I'm certainly no coder and it hasn't done the trick.  

Any help would be greatly appreciated.  I miss my robot wife giving me directions to a parking spot...

Lath

**Comment by Lathomere** [comment]
Alas, no joy.  Though there's nothing that says I've even renamed the files properly, but I did run up the line of all the various language .json files.  
Fingers crossed that something comes about.
Thanks for the idea @LuPoNe81 !

Lath

**Comment by Tkael** [comment]
@Lathomere A copy of your log files could help determine whether this is a related or unrelated issue. If your log is free of the Files.Read error noted above, try the generic troubleshooting for being unable to start EDDI? https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md#eddi-doesnt-start-or-crashes-on-startup?

**Comment by Lathomere** [comment]
Hi Tkael,  you'll have to forgive me, but I'm not even sure where the log file is.  I'm more than happy to post them.  I'll check and see if I can find it.
L

**Comment by Tkael** [comment]
Looks like you found VoiceAttack's log. EDDI's log files are located at `%APPDATA%/EDDI`

**Comment by Lathomere** [comment]
Gotcha, 
  I was hoping that the general Windows Log would catch it.  Have now found it and here it is in all its glory:

2018-07-02T12:50:21 [Info] VoiceAttackPlugin:VA_Init1 Initialising EDDI VoiceAttack plugin 
2018-07-02T12:50:21 [Info] EDDI:.ctor EDDI 3.0.1-rc3 starting 
2018-07-02T12:50:21 [Info] EDDI:.ctor On live 
2018-07-02T12:50:23 [Info] CargoMonitor:initializeCargoMonitor Initialised Cargo monitor 1.0.0 
2018-07-02T12:50:23 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name tg_shipsystemdata in resource EddiDataDefinitions.Properties.Materials 
2018-07-02T12:50:23 [Info] MaterialMonitor:.ctor Initialised Material monitor 1.0.0 
2018-07-02T12:50:23 [Info] ShipMonitor:.ctor Initialised Ship monitor 1.0.0 
2018-07-02T12:50:23 [Info] StatusMonitor:.ctor Initialised Status monitor 1.0.0 
2018-07-02T12:50:23 [Info] EDDNResponder:.ctor Initialised EDDN responder 1.0.0 
2018-07-02T12:50:23 [Info] EDSMResponder:.ctor Initialised EDSM responder 1.0.0 
2018-07-02T12:50:23 [Info] SpeechResponder:.ctor Initialised Speech responder 1.0.0 
2018-07-02T12:50:23 [Info] VoiceAttackResponder:.ctor Started VoiceAttack responder 
2018-07-02T12:50:23 [Error] Files:Read File C:\Users\ObsidianHawk\AppData\Roaming\EDDI\credentials.json not found System.IO.FileNotFoundException: Could not find file 'C:\Users\ObsidianHawk\AppData\Roaming\EDDI\credentials.json'.
File name: 'C:\Users\ObsidianHawk\AppData\Roaming\EDDI\credentials.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Utilities.Files.Read(String name)
2018-07-02T12:50:23 [Info] EDDI:.ctor EDDI access to the companion app is disabled 
2018-07-02T12:50:23 [Error] Files:Read File C:\Users\ObsidianHawk\AppData\Roaming\EDDI\credentials.json not found System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-07-02T12:50:23 [Info] EDDI:.ctor EDDI access to EDSM is disabled 
2018-07-02T12:50:23 [Info] EDDI:.ctor EDDI 3.0.1-rc3 initialised 
2018-07-02T12:50:23 [Info] EDDI:Start Starting keepalive for EDDP monitor 
2018-07-02T12:50:23 [Info] EDDI:Start Starting keepalive for Galnet monitor 
2018-07-02T12:50:23 [Info] EDDI:Start Starting keepalive for Journal monitor 
2018-07-02T12:50:23 [Info] EDDI:keepAlive Starting EDDP monitor (0) 
2018-07-02T12:50:23 [Info] EDDI:Start Starting keepalive for Status monitor 
2018-07-02T12:50:23 [Info] EDDI:keepAlive Starting Galnet monitor (0) 
2018-07-02T12:50:23 [Info] EDDI:keepAlive Starting Status monitor (0) 
2018-07-02T12:50:23 [Info] EDDI:Start Started EDDN responder 
2018-07-02T12:50:23 [Info] EDDI:keepAlive Starting Journal monitor (0) 
2018-07-02T12:50:23 [Error] VoiceAttackPlugin:VA_Init1 Failed to initialize VoiceAttack plugin System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiEdsmResponder.EDSMResponder.Reload()
   at EddiEdsmResponder.EDSMResponder.Start()
   at Eddi.EDDI.Start()
   at EddiVoiceAttackResponder.VoiceAttackPlugin.VA_Init1(Object vaProxy)
2018-07-02T12:50:23 [Error] VoiceAttackPlugin:VA_Init1 Failed to initialize VoiceAttack plugin System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-07-02T12:50:23 [Info] EDDI:eventFileHeader On live 

Thanks for the help on this, and apologies for being "that guy".

L

**Comment by Lathomere** [comment]
Ok issue resolved.  Just cleared out the EDDI folder from VA and reinstalled.  All is well!

Thanks @LuPoNe81 and @Tkael for the help!

Lath
