### ISSUE TITLE
CTD in all 3.0.x versions - EDDI does not gracefully handle sql database corruption

### ISSUE THREAD

**Issue by hippocratical** [EDCD/EDDI#820]
## EDDI version in which issue found
All 3.0.x

## Steps to reproduce

EDDI crashes to desktop after being open for about 5 seconds. This didn't happen in versions 2.x and prior. I have uninstalled/reinstalled to no avail. Running as administer, or installing as admin, doesn't help.

## Expected
for it not to crash

Here's a log:

2018-08-31T01:43:22 [Info] EDDI:.ctor EDDI 3.0.3-rc1 starting 
2018-08-31T01:43:22 [Info] EDDI:.ctor On live 
2018-08-31T01:43:22 [Info] CargoMonitor:initializeCargoMonitor Initialised Cargo monitor 1.0.0 
2018-08-31T01:43:22 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name tg_shipsystemdata in resource EddiDataDefinitions.Properties.Materials 
2018-08-31T01:43:23 [Info] MaterialMonitor:.ctor Initialised Material monitor 1.0.0 
2018-08-31T01:43:23 [Info] ShipMonitor:.ctor Initialised Ship monitor 1.0.0 
2018-08-31T01:43:23 [Info] StatusMonitor:.ctor Initialised Status monitor 1.0.0 
2018-08-31T01:43:23 [Info] EDDNResponder:.ctor Initialised EDDN responder 1.0.0 
2018-08-31T01:43:23 [Info] EDSMResponder:.ctor Initialised EDSM responder 1.0.0 
2018-08-31T01:43:23 [Info] SpeechResponder:.ctor Initialised Speech responder 1.0.0 
2018-08-31T01:43:23 [Info] VoiceAttackResponder:.ctor Started VoiceAttack responder 
2018-08-31T01:43:23 [Error] Files:Read File C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json not found System.IO.FileNotFoundException: Could not find file 'C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json'.
File name: 'C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Utilities.Files.Read(String name)
2018-08-31T01:43:23 [Info] EDDI:.ctor EDDI access to the companion app is disabled 
2018-08-31T01:43:23 [Error] Files:Read File C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json not found System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-08-31T01:43:23 [Info] EDDI:.ctor EDDI access to EDSM is enabled 
2018-08-31T01:43:23 [Info] EDDI:.ctor EDDI 3.0.3-rc1 initialised 
2018-08-31T01:43:23 [Info] EDDI:Start Starting keepalive for EDDP monitor 
2018-08-31T01:43:23 [Info] EDDI:Start Starting keepalive for Journal monitor 
2018-08-31T01:43:23 [Info] EDDI:keepAlive Starting EDDP monitor (0) 
2018-08-31T01:43:23 [Info] EDDI:keepAlive Starting Journal monitor (0) 
2018-08-31T01:43:23 [Info] EDDI:Start Starting keepalive for Status monitor 
2018-08-31T01:43:23 [Info] EDDI:keepAlive Starting Status monitor (0) 
2018-08-31T01:43:23 [Info] EDDI:Start Started EDDN responder 
2018-08-31T01:43:23 [Info] EDDI:eventFileHeader On live 
2018-08-31T01:43:24 [Info] EDDI:Start Started EDSM responder 
2018-08-31T01:43:24 [Info] EDDI:Start Started Speech responder 
2018-08-31T01:43:24 [Info] StarMapService:Sync Syncing with EDSM 
2018-08-31T01:43:24 [Info] EDDI:Start Started VoiceAttack responder 
2018-08-31T01:43:24 [Error] Files:Read File C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json not found System.IO.FileNotFoundException: Could not find file 'C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json'.
File name: 'C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Utilities.Files.Read(String name)
2018-08-31T01:43:24 [Error] Files:Read File C:\Users\Colossus\AppData\Roaming\EDDI\credentials.json not found System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-08-31T01:43:25 [Warning] StarSystemSqLiteRepository:GetStarSystem Problem reading data from database, re-obtaining from source. 
2018-08-31T01:43:25 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name ancientkey in resource EddiDataDefinitions.Properties.Commodities 
2018-08-31T01:43:25 [Warning] StarSystemSqLiteRepository:GetStarSystem Problem obtaining data from source: code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at EddiDataProviderService.StarSystemSqLiteRepository.updateStarSystem(StarSystem system)
   at EddiDataProviderService.StarSystemSqLiteRepository.GetStarSystem(String name, Boolean refreshIfOutdated) 
2018-08-31T01:43:25 [Warning] StarSystemSqLiteRepository:GetStarSystem Problem reading data from database, re-obtaining from source. 
2018-08-31T01:43:26 [Warning] StarSystemSqLiteRepository:GetStarSystem Problem obtaining data from source: code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at EddiDataProviderService.StarSystemSqLiteRepository.updateStarSystem(StarSystem system)
   at EddiDataProviderService.StarSystemSqLiteRepository.GetStarSystem(String name, Boolean refreshIfOutdated) 
2018-08-31T01:43:26 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID 95a62f8e-dfe7-4b0f-89b5-0d4852af0335:code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at EddiDataProviderService.StarSystemSqLiteRepository.insertStarSystem(StarSystem system)
   at EddiDataProviderService.StarSystemSqLiteRepository.GetOrCreateStarSystem(String name, Boolean fetchIfMissing)
   at EddiStarMapService.StarMapService.SyncUpdate(Dictionary`2 comments, List`1 syncSystems, Dictionary`2 systemLogs, Nullable`1 since)
   at EddiStarMapService.StarMapService.Sync(Nullable`1 since)
   at EddiEdsmResponder.EDSMResponder.<>c__DisplayClass10_0.<Reload>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 

------------------------------

The "database disk image is malformed" part catches my eye.

**Comment by Tkael** [comment]
```
2018-08-31T01:43:25 [Warning] StarSystemSqLiteRepository:GetStarSystem Problem obtaining data from source: code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
```
Yep. Looks like you probably have a corrupt data file. 
Navigate to %APPDATA%/Roaming/EDDI and delete EDDI.sqlite. Then try to restart EDDI.

**Comment by hippocratical** [comment]
That fixed it! Thanks so much - I was pulling my hair out trying to solve that.

**Comment by Tkael** [comment]
Reopening until we can harden EDDI against similar errors.

**Comment by richardbuckle** [comment]
Mixed feelings here. Defensive programming by all means, but I'd eschew any attempt to repair. The SQL is discardable after all, so I'd offer that option only.

**Comment by Tkael** [comment]
Agreed. The thing to do would probably be to discard and (if signed in with EDSM credentials) to re-sync visited systems from EDSM.

**Comment by richardbuckle** [comment]
For 3.1, catch `[Warning] StarSystemSqLiteRepository:GetStarSystem Problem obtaining data from source: code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed` and recover by closing and renaming the old SQl file and starting with a clean one

**Comment by Tkael** [comment]
I've wrapped this into my working branch.
