### ISSUE TITLE
Unrecognized Commodity Definition EliteID 128888499

### ISSUE THREAD

**Issue by Roming22** [EDCD/EDDI#824]
## EDDI version in which issue found
3.0.2 VA plugin

## Steps to reproduce
Unknown

## Expected
No errors.

## Observed
EDDI logs are full of
```
2018-09-01T20:54:14 [Error] EDDI:conditionallyRefreshProfile Exception obtaining profile System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EddiDataDefinitions.CommodityDefinition.CommodityDefinitionFromEliteID(Int64 id)
   at EddiDataDefinitions.CommodityMarketQuote.FromCapiJson(JObject capiJSON)
   at EddiCompanionAppService.CompanionAppService.CommodityQuotesFromProfile(JObject json)
   at EddiCompanionAppService.CompanionAppService.Station(String systemName)
   at Eddi.EDDI.conditionallyRefreshProfile()
2018-09-01T20:54:14 [Error] EDDI:conditionallyRefreshProfile Exception obtaining profile System.Collections.Generic.Dictionary`2[System.String,System.Object]
2018-09-01T20:54:14 [Info] CommodityDefinition:CommodityDefinitionFromEliteID Unrecognized Commodity Definition EliteID 128888499 
```

## Investigation
It seems like I have an invalid identifier somewhere.
I looked at the content of the JSON files in %APPDATA%\Roaming\EDDI but could not any reference to the ID.
I looked at EDDI.sqlite, but it seems to contain only a list of systems, with no references to cargo or commodities.

[eddi.log](https://github.com/EDCD/EDDI/files/2342811/eddi.log)

**Comment by Tkael** [comment]
That'd be the new Guardian `Ancient Key` commodity. Should be incorporated into the next release.

**Comment by Tkael** [comment]
Actually, this is already incorporated in 3.0.3-rc1. No need to wait. You can download it here: https://github.com/EDCD/EDDI/releases
