### ISSUE TITLE
Errors thrown when landing at any station.

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#833]
## EDDI version in which issue found
3.03 under VA

## Steps to reproduce

1. Land at a station
2. [Find errors in eddi.log]

## Expected
[No logged errors]

## Observed

2018-09-08T14:19:17 [Error] EDDI:conditionallyRefreshProfile Exception obtaining profile System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EddiCompanionAppService.CompanionAppService.OutfittingFromProfile(JObject json)
   at EddiCompanionAppService.CompanionAppService.Station(String systemName)
   at Eddi.EDDI.conditionallyRefreshProfile()

….repeats 5 more times

2018-09-08T14:19:17 [Info] EDDI:conditionallyRefreshProfile Maximum attempts reached; giving up on request 

## Investigation
[Looking to understand what is being done here?]
What is `private void conditionallyRefreshProfile()` attempting to do and why?
Why does it fail?

Thanks.

**Comment by Tkael** [comment]
That's the connection to the Frontier API. If you are logged in to the Frontier API, EDDI will try to refresh data as soon as you dock (this is what is happening immediately prior to the `Market information updated` event. It will also refresh when you undock and about every 15 minutes otherwise.

Are you logged in to the Frontier API? Did you recently need to re-sign in?

**Comment by Hoodathunk** [comment]
Interesting, as the API crashed hard last night... It’s back up now and I had to re-log-in.

At the least, we may need to look into EDDI ‘behaving’ when the API server is down.

**Comment by Tkael** [comment]
Hmm. Is this happening for you every time you dock? Since you have some knowledge of Visual Studios, do you think that you can catch it in the debugger and determine which key is missing? The message you provided doesn't include code lines describing where in the method the problem occurred or which key was missing.

**Comment by rodan123** [comment]
I think I have narrowed it down to `public static List<Module> OutfittingFromProfile(JObject json)` in EDDI\CompanionAppService\CompanionAppService.cs.  It seems to error out always when encountering an entry for Hpt_DumbfireMissileRack_Fixed. This station errors for Hpt_DumbfireMissileRack_Fixed_Large. At other stations it was Hpt_DumbfireMissileRack_Fixed_Medium. Don't know why. Any idea? Stations that haven't that module seem to work OK.

**JSON**
...
        _"128777346": {
      "id": 128777346,
      "category": "module",
      "name": "Int_DroneControl_Repair_Size7_Class5",
      "cost": 6823440,
      "sku": null
    },
    "128841594": {
      "id": 128841594,
      "category": "module",
      "name": "Int_DroneControl_Recon_Size7_Class1",
      "cost": 596895,
      "sku": null
    },
    "128891602": {
      "id": 128891602,
      "category": "weapon",
      "name": "Hpt_DumbfireMissileRack_Fixed_Large",
      "cost": 896367,
      "sku": "ELITE_HORIZONS_V_PLANETARY_LANDINGS"
    }
  }
}_

 **LOGFILE**
…

_2018-09-09T19:58:59 [Info] CompanionAppService:OutfittingFromProfile Hpt_Cannon_Fixed_Large 
2018-09-09T19:58:59 [Info] CompanionAppService:OutfittingFromProfile Hpt_MultiCannon_Turret_Large 
2018-09-09T19:58:59 [Info] CompanionAppService:OutfittingFromProfile Hpt_DumbfireMissileRack_Fixed_Large 
2018-09-09T19:58:59 [Error] EDDI:conditionallyRefreshProfile Exception obtaining profile System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EddiCompanionAppService.CompanionAppService.OutfittingFromProfile(JObject json)
   at EddiCompanionAppService.CompanionAppService.Station(String systemName)
   at Eddi.EDDI.conditionallyRefreshProfile()
2018-09-09T19:58:59 [Info] EDDI:conditionallyRefreshProfile Maximum attempts reached; giving up on request_

**Comment by Tkael** [comment]
Thanks. That should be very helpful.

**Comment by c0dejunKie** [comment]
I just felt like chiming in and letting you all know that I to have all these same errors in my log.  My log started to be flooded with these errors over the last 2 weeks.  Just so you know that this issue is not just affecting one person but everyone that uses EDDI.

I was forced to relog into frontiers API this morning after the update to v3.1.0-b1 and the errors are still there.

**Comment by Hoodathunk** [comment]
Had some time to look at this. The key for large 'Dumbfire' missiles is definitely wrong.

Should be 128891602 and ModuleDefinitions has it as 128666762, hence key not found.

This jives with the EDDB.io modules archive. Not sure how/where this got screwed up, but easily fixed.

**Comment by Hoodathunk** [comment]
PR #865 merged
