### ISSUE TITLE
Cargo Monitor not handling expired missions 

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#855]
## EDDI version in which issue found
3.1-b1
## Steps to reproduce

1. Accept mission (in this case an assassination mission)
2. Allow mission to expire

## Expected
No errors thrown, event handled gracefully.

## Observed
`[Warning] EDDI:OnEvent Monitor failed System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiCargoMonitor.CargoMonitor._handleMissionExpiredEvent(MissionExpiredEvent event)
   at EddiCargoMonitor.CargoMonitor.PostHandle(Event event)
   at Eddi.EDDI.<>c__DisplayClass101_2.<OnEvent>b__1()
2018-09-26T21:06:20 [Warning] EDDI:OnEvent Monitor failed System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiCargoMonitor.CargoMonitor._handleMissionExpiredEvent(MissionExpiredEvent event)
   at EddiCargoMonitor.CargoMonitor.PostHandle(Event event)
   at Eddi.EDDI.<>c__DisplayClass101_2.<OnEvent>b__1()`

## Investigation
None

**Comment by Hoodathunk** [comment]
It's handling cargo related mission expirations, but producing null ref object exceptions for non-cargo ones. Thanks for the report. Added fix to PR #854

**Comment by Hoodathunk** [comment]
PR #854 Merged.
