### ISSUE TITLE
Error reported when ship ID set to "$$$$$$"

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#889]
## EDDI version in which issue found
3.1-b3 standalone

## Steps to reproduce

1. In livery, set your ship ID to "$$$$$$".

## Expected
Ship renamed script runs without error.

## Observed
Error reported: "Failed to resolve the: Ship renamed script. System.InvalidOperationException: Sequence contains no elements"

## Investigation
[reddit report](https://www.reddit.com/r/EliteDangerous/comments/9ro7uf/eddi_31b3_released/e8j2i3b/)

Stack trace:

2018-10-27T17:57:59 [Warning] ScriptResolver:resolveScript Failed to resolve the: Ship renamed script. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at EddiSpeechService.Translations.ICAO(String callsign, Boolean passDash) in C:\dev\EDDI\SpeechService\Translations.cs:line 570
   at EddiSpeechResponder.ScriptResolver.<>c.<buildStore>b__13_19(IList`1 values) in C:\dev\EDDI\SpeechResponder\ScriptResolver.cs:line 477
   at Cottle.Functions.NativeFunction.<>c__DisplayClass14_0.<.ctor>b__0(IList`1 v, IStore s, TextWriter o)
   at Cottle.Functions.NativeFunction.Execute(IList`1 arguments, IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.EchoNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.SimpleDocument.Render(IStore store, TextWriter writer)
   at Cottle.Documents.AbstractDocument.Render(IStore store)
   at EddiSpeechResponder.ScriptResolver.resolveScript(String script, BuiltinStore store, Boolean master, Script scriptObject) in C:\dev\EDDI\SpeechResponder\ScriptResolver.cs:line 88

**Comment by richardbuckle** [comment]
The ICAO conversion is failing because the ID has no convertible characters. I noted that in-game, if you set traffic control to use your ship ID, it merely says your ship manufacturer, i.e. the ID in ICAO is an empty string.
